apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hellouv
  name: hellouv
spec:
  containers:
  - command: ["/bin/sh", "-c","ping -i 10 8.8.8.8 > /tmp/adhoc.txt"]
    image: alpine
    name: hellouv
  restartPolicy: Never
