apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello2uv
  name: hello2uv
spec:
  containers:
  - command: ["/bin/sh", "-c"]
    args: [" ping  8.8.8.8 "]
    image: alpine
    name: hello2uv
  restartPolicy: Never


#kubectl get pod -o wide |  awk '{print $6 }' | grep 1 >> ip.txt
