apiVersion: v1
kind: Pod
metadata:
  labels:
    run: hello1uv
  name: hello1uv
spec:
  containers:
  - command: ["/bin/sh", "-c","ping 8.8.8.8"]
    image: busybox
    workingDir: /opt
    name: hello1uv
  restartPolicy: Never



#kubectl cp hellouv:/tmp/adhoc.txt adhoc.txt
#kubectl cp adhoc.txt hello1uv:/opt/adhoc.txt
#kubectl exec -it hello1uv -c hello1uv -- /bin/sh -c "cat adhoc.txt | wc -c > count.txt"
